FROM node:20-alpine
WORKDIR /app
COPY package.json ./
RUN npm install
COPY server.js ./
COPY public/ ./public/
ENV PORT=8090
ENV NODE_ENV=development
CMD ["npx", "nodemon", "--watch", "server.js", "server.js"]
